<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="MAIN_COE_Auswertung" Id="{4be8eb0e-eb8a-4a8c-aa30-ca78f43e7d4b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_COE_Auswertung
VAR
	auswertung: COE_Auswertung;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[auswertung();]]></ST>
    </Implementation>
    <LineIds Name="MAIN_COE_Auswertung">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>