///////////////////////////////////////////////////////////////////////////////
// velocityConverterToCartesianServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_velocityConverterToCartesian = 0x3F000000;
#define SRVNAME_VELOCITYCONVERTERTOCARTESIAN "velocityConverterToCartesian"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_velocityConverterToCartesianCvelocityConverterToCartesian = {0x567d3eae,0xb93e,0x4490,{0xba,0xde,0x9b,0xb5,0x6f,0xbd,0xba,0xbf}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_velocityConverterToCartesianParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _velocityConverterToCartesianParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} velocityConverterToCartesianParameter, *PvelocityConverterToCartesianParameter;

typedef struct _velocityConverterToCartesianInputs
{
	double velocityFromMotor1;
	double velocityFromMotor2;
	double velocityFromMotor3;
} velocityConverterToCartesianInputs, *PvelocityConverterToCartesianInputs;

typedef struct _velocityConverterToCartesianOutputs
{
	double vXCartesianFromMotors;
	double vYCartesianFromMotors;
	double thetaCartesianFromMotors;
} velocityConverterToCartesianOutputs, *PvelocityConverterToCartesianOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_velocityConverterToCartesianInputs 0
#define ADI_velocityConverterToCartesianOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
