///////////////////////////////////////////////////////////////////////////////
// velocityConverterToMotorsClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "velocityConverterToMotorsClassFactory.h"
#include "velocityConverterToMotorsServices.h"
#include "velocityConverterToMotorsVersion.h"
#include "velocityConverterToMotors.h"

BEGIN_CLASS_MAP(CvelocityConverterToMotorsClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_velocityConverterToMotorsCvelocityConverterToMotors, SRVNAME_VELOCITYCONVERTERTOMOTORS "!CvelocityConverterToMotors", CvelocityConverterToMotors)
///</AutoGeneratedContent>
END_CLASS_MAP()

CvelocityConverterToMotorsClassFactory::CvelocityConverterToMotorsClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_VELOCITYCONVERTERTOMOTORS)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(velocityConverterToMotors));
#endif //defined(TCDBG_UNIT_VERSION)
}

