///////////////////////////////////////////////////////////////////////////////
// velocityConverterToMotors.h
#pragma once

#include "velocityConverterToMotorsInterfaces.h"

class CvelocityConverterToMotors 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_velocityConverterToMotorsCvelocityConverterToMotors)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CvelocityConverterToMotors();
	virtual	~CvelocityConverterToMotors();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Tracing
	CTcTrace m_Trace;

	double vX;
	double vY;
	double vTheta;
	double v0;
	double v1;
	double v2;
	double f;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	velocityConverterToMotorsParameter m_Parameter;
	velocityConverterToMotorsInputs m_Inputs;
	velocityConverterToMotorsOutputs m_Outputs;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>

	// TODO: Custom variable
	UINT m_counter;
};
