<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="MAIN" Id="{83da6505-1eb3-48a2-b593-db0aa655616f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	udp1 : UDP_Communication;
	sPaketinhalt	: STRING;
	pDataString: T_MaxString;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[udp1();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>