<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.3">
  <POU Name="MAIN" Id="{f58e1d9e-fe57-40b8-989d-e2e4f67a8ce2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bLED1	AT%Q* : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[bLED1 := TRUE;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>